name: Daily RSI Screener

on:
  schedule:
    # 3:00 PM IST is 9:30 AM UTC
    - cron: '00 10 * * *'
  workflow_dispatch: # Allows you to run it manually for testing

permissions:
  contents: write  # Allows GitHub to save the index.html to your repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Screener
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python RSI_Web.py
        
      - name: Commit and Push Website
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Update RSI Report" || echo "No changes to commit"
      
